import type { Comment } from "@/lib/notion/types";

/** 리뷰 ID별 더미 댓글 데이터 */
export const DUMMY_COMMENTS: Record<string, Comment[]> = {
  "rev-001": [
    {
      id: "cmt-001-1",
      reviewId: "rev-001",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "파친코는 정말 묵직한 책이죠. 4대에 걸친 이야기인데도 지루할 틈이 없었어요.",
      createdAt: "2026-04-02T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-001-2",
      reviewId: "rev-001",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "이민진 작가의 문체가 너무 좋아요. 번역본인데도 그 무게감이 그대로 전해졌어요.",
      createdAt: "2026-04-02T11:30:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-001-3",
      reviewId: "rev-001",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "역사적 배경 지식 없이 읽어도 충분히 몰입되더라고요. 강력 추천합니다.",
      createdAt: "2026-04-02T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-001-4",
      reviewId: "rev-001",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "마지막 장 읽으면서 눈물이 났어요. 오래 기억에 남을 것 같아요.",
      createdAt: "2026-04-03T08:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-001-5",
      reviewId: "rev-001",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "Apple TV 드라마로도 나왔는데 책이 훨씬 좋았어요.",
      createdAt: "2026-04-03T10:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-002": [
    {
      id: "cmt-002-1",
      reviewId: "rev-002",
      author: "김수진",
      authorEmail: "sujin@example.com",
      body: "인지 혁명 파트가 제일 흥미로웠어요. 허구를 믿는 능력이 인류를 지배하게 했다는 관점이 신선했어요.",
      createdAt: "2026-04-04T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-002-2",
      reviewId: "rev-002",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "농업 혁명을 '사기'라고 표현한 부분에서 엄청 공감했어요.",
      createdAt: "2026-04-04T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-002-3",
      reviewId: "rev-002",
      author: "윤태호",
      authorEmail: "taeho@example.com",
      body: "호모 데우스도 함께 읽으면 더 좋을 것 같아요.",
      createdAt: "2026-04-04T13:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-002-4",
      reviewId: "rev-002",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "분량이 상당한데 생각보다 쉽게 읽혔어요.",
      createdAt: "2026-04-05T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-002-5",
      reviewId: "rev-002",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "하라리의 단순화가 좀 과하다는 비판도 있지만, 큰 그림을 보기에는 최고의 책이라고 생각해요.",
      createdAt: "2026-04-05T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-002-6",
      reviewId: "rev-002",
      author: "오나연",
      authorEmail: "nayeon@example.com",
      body: "역사책을 이렇게 흥미롭게 쓸 수 있다는 게 놀라웠어요.",
      createdAt: "2026-04-05T14:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-003": [
    {
      id: "cmt-003-1",
      reviewId: "rev-003",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "감정을 느끼지 못한다는 설정이 오히려 독자의 감정을 더 자극하는 것 같아요.",
      createdAt: "2026-04-06T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-003-2",
      reviewId: "rev-003",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "곤이 캐릭터가 너무 매력적이었어요. 처음엔 나쁜 애인 줄 알았는데.",
      createdAt: "2026-04-06T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-003-3",
      reviewId: "rev-003",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "마지막 문장이 오래 머릿속에 맴돌았어요.",
      createdAt: "2026-04-06T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-003-4",
      reviewId: "rev-003",
      author: "임소현",
      authorEmail: "sohyun@example.com",
      body: "한국 소설 중에서 손꼽히는 수작이라고 생각해요.",
      createdAt: "2026-04-07T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-003-5",
      reviewId: "rev-003",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "청소년 소설로 분류되지만 어른이 읽어도 충분히 깊은 책이에요.",
      createdAt: "2026-04-07T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-004": [
    {
      id: "cmt-004-1",
      reviewId: "rev-004",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "MVP 개념을 제대로 이해하게 된 책이에요. 사이드 프로젝트에 바로 적용해봤어요.",
      createdAt: "2026-04-08T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-004-2",
      reviewId: "rev-004",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "Build-Measure-Learn 루프가 핵심인데, 실천하기가 쉽지 않더라고요.",
      createdAt: "2026-04-08T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-004-3",
      reviewId: "rev-004",
      author: "김수진",
      authorEmail: "sujin@example.com",
      body: "스타트업이 아니어도 조직 내 새 기능 개발할 때 적용할 수 있어요.",
      createdAt: "2026-04-08T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-004-4",
      reviewId: "rev-004",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "피봇 사례들이 아주 구체적이어서 도움이 됐어요.",
      createdAt: "2026-04-09T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-004-5",
      reviewId: "rev-004",
      author: "오나연",
      authorEmail: "nayeon@example.com",
      body: "같이 읽고 싶은 책: 고객 개발 방법론과 묶어서 읽으면 더욱 깊어요.",
      createdAt: "2026-04-09T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-005": [
    {
      id: "cmt-005-1",
      reviewId: "rev-005",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "SF 입문으로 적합한지 모르겠지만, 세계관 자체가 너무 방대해서 압도당했어요.",
      createdAt: "2026-04-10T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-005-2",
      reviewId: "rev-005",
      author: "김수진",
      authorEmail: "sujin@example.com",
      body: "영화보다 책이 훨씬 깊이 있어요. 스파이스의 상징성을 영화에서는 다 못 담았죠.",
      createdAt: "2026-04-10T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-005-3",
      reviewId: "rev-005",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "폴 아트레이데스의 성장 서사가 고전적이지만 여전히 설레게 만들어요.",
      createdAt: "2026-04-10T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-005-4",
      reviewId: "rev-005",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "허버트가 세계를 이렇게 치밀하게 구축했다는 게 믿기지 않아요.",
      createdAt: "2026-04-11T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-005-5",
      reviewId: "rev-005",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "2편도 읽고 싶어졌어요. 후속작들 어떤가요?",
      createdAt: "2026-04-11T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-005-6",
      reviewId: "rev-005",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "환경과 생태에 대한 메시지가 오늘날에도 유효한 것 같아요.",
      createdAt: "2026-04-11T14:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-006": [
    {
      id: "cmt-006-1",
      reviewId: "rev-006",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "불편하지만 강렬하다는 표현이 딱 맞아요. 읽는 내내 마음이 무거웠어요.",
      createdAt: "2026-04-12T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-006-2",
      reviewId: "rev-006",
      author: "임소현",
      authorEmail: "sohyun@example.com",
      body: "노벨상 받을 만한 작품이라는 걸 이 소설로 처음 실감했어요.",
      createdAt: "2026-04-12T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-006-3",
      reviewId: "rev-006",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "한강 작가의 소설 중 어떤 걸 먼저 읽으면 좋을까요?",
      createdAt: "2026-04-12T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-006-4",
      reviewId: "rev-006",
      author: "오나연",
      authorEmail: "nayeon@example.com",
      body: "영혜의 선택이 저항인지 붕괴인지 계속 생각하게 돼요.",
      createdAt: "2026-04-13T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-006-5",
      reviewId: "rev-006",
      author: "윤태호",
      authorEmail: "taeho@example.com",
      body: "짧지만 강렬한 독서 경험이었어요.",
      createdAt: "2026-04-13T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-007": [
    {
      id: "cmt-007-1",
      reviewId: "rev-007",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "집중력에 대한 책인데 정작 읽다가 여러 번 딴 생각이 났어요 ㅎㅎ.",
      createdAt: "2026-04-14T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-007-2",
      reviewId: "rev-007",
      author: "김수진",
      authorEmail: "sujin@example.com",
      body: "도미노 이미지가 계속 기억에 남아요. 큰 목표를 작은 것들로 쌓아가는 개념.",
      createdAt: "2026-04-14T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-007-3",
      reviewId: "rev-007",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "'멀티태스킹은 신화다'라는 파트가 가장 공감됐어요.",
      createdAt: "2026-04-14T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-007-4",
      reviewId: "rev-007",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "실천법이 구체적이지 않아서 조금 아쉬웠어요.",
      createdAt: "2026-04-15T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-007-5",
      reviewId: "rev-007",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "딥 워크와 함께 읽으면 시너지가 있을 것 같아요.",
      createdAt: "2026-04-15T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-008": [
    {
      id: "cmt-008-1",
      reviewId: "rev-008",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "'중요한 건 눈에 보이지 않아' — 이 문장 하나로 이미 충분한 책이에요.",
      createdAt: "2026-04-16T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-008-2",
      reviewId: "rev-008",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "어릴 때는 그냥 예쁜 이야기인 줄 알았는데 지금 읽으니 완전히 다르게 읽혀요.",
      createdAt: "2026-04-16T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-008-3",
      reviewId: "rev-008",
      author: "윤태호",
      authorEmail: "taeho@example.com",
      body: "여우와 장미의 대화가 인상적이었어요.",
      createdAt: "2026-04-16T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-008-4",
      reviewId: "rev-008",
      author: "오나연",
      authorEmail: "nayeon@example.com",
      body: "짧은 분량에 이렇게 많은 의미를 담다니. 역시 고전이에요.",
      createdAt: "2026-04-17T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-008-5",
      reviewId: "rev-008",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "삽화가 정말 예쁜데, 한국어판 번역도 잘 됐더라고요.",
      createdAt: "2026-04-17T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-008-6",
      reviewId: "rev-008",
      author: "임소현",
      authorEmail: "sohyun@example.com",
      body: "제가 직접 고른 책인데 다들 좋아해주셔서 기뻤어요.",
      createdAt: "2026-04-17T14:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-009": [
    {
      id: "cmt-009-1",
      reviewId: "rev-009",
      author: "김수진",
      authorEmail: "sujin@example.com",
      body: "지리결정론에 동의하기 어려운 부분도 있지만 자극적인 논점이 많았어요.",
      createdAt: "2026-04-18T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-009-2",
      reviewId: "rev-009",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "왜 어떤 나라는 잘 살고 어떤 나라는 못 사는지에 대한 시각을 바꿔준 책이에요.",
      createdAt: "2026-04-18T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-009-3",
      reviewId: "rev-009",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "동식물의 가축화 가능성 챕터가 가장 흥미로웠어요.",
      createdAt: "2026-04-18T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-009-4",
      reviewId: "rev-009",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "사피엔스와 비교해서 읽으면 좋을 것 같아요.",
      createdAt: "2026-04-19T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-009-5",
      reviewId: "rev-009",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "분량이 많지만 한 번 빠지면 끝까지 읽게 돼요.",
      createdAt: "2026-04-19T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-010": [
    {
      id: "cmt-010-1",
      reviewId: "rev-010",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "마법 세계를 처음 접하는 해리의 눈을 통해 독자도 함께 경이로움을 느끼게 돼요.",
      createdAt: "2026-04-20T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-010-2",
      reviewId: "rev-010",
      author: "윤태호",
      authorEmail: "taeho@example.com",
      body: "어릴 때 읽은 책인데 모임에서 다시 읽으니 작가의 복선 구성이 더 보이더라고요.",
      createdAt: "2026-04-20T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-010-3",
      reviewId: "rev-010",
      author: "임소현",
      authorEmail: "sohyun@example.com",
      body: "헤르미온느가 역시 최고예요.",
      createdAt: "2026-04-20T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-010-4",
      reviewId: "rev-010",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "마법 설정이 얼마나 일관성 있게 유지되는지 새삼 감탄했어요.",
      createdAt: "2026-04-21T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-010-5",
      reviewId: "rev-010",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "다음 모임 책으로 2권 어떨까요?",
      createdAt: "2026-04-21T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-011": [
    {
      id: "cmt-011-1",
      reviewId: "rev-011",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "내가 세상을 얼마나 왜곡해서 보고 있는지 반성하게 됐어요.",
      createdAt: "2026-04-22T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-011-2",
      reviewId: "rev-011",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "'세상은 생각보다 나쁘지 않다'는 메시지가 요즘 같은 시대에 더욱 필요해요.",
      createdAt: "2026-04-22T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-011-3",
      reviewId: "rev-011",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "테드 강연도 굉장히 좋으니 함께 추천해요.",
      createdAt: "2026-04-22T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-011-4",
      reviewId: "rev-011",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "10가지 본능 중 '공포 본능'이 가장 와 닿았어요.",
      createdAt: "2026-04-23T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-011-5",
      reviewId: "rev-011",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "저도 이 책 읽은 이후로 뉴스를 보는 방식이 달라졌어요.",
      createdAt: "2026-04-23T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-012": [
    {
      id: "cmt-012-1",
      reviewId: "rev-012",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "독점이 나쁜 게 아니라는 주장이 처음엔 당황스러웠지만 논리를 따라가다 보니 수긍이 됐어요.",
      createdAt: "2026-04-24T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-012-2",
      reviewId: "rev-012",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "피터 틸의 철학이 엿보이는 책이에요. 동의 여부와 무관하게 생각을 자극해요.",
      createdAt: "2026-04-24T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-012-3",
      reviewId: "rev-012",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "비밀에 관한 챕터가 가장 인상적이었어요.",
      createdAt: "2026-04-24T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-012-4",
      reviewId: "rev-012",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "린 스타트업과 비교해서 읽으면 재미있을 것 같아요. 관점이 많이 달라요.",
      createdAt: "2026-04-25T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-012-5",
      reviewId: "rev-012",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "짧고 밀도 있어서 경영 책치고는 빨리 읽혔어요.",
      createdAt: "2026-04-25T11:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-013": [
    {
      id: "cmt-013-1",
      reviewId: "rev-013",
      author: "이지은",
      authorEmail: "jieun@example.com",
      body: "디지털 감시 시대에 다시 읽으니 오싹함이 배로 느껴졌어요.",
      createdAt: "2026-04-26T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-013-2",
      reviewId: "rev-013",
      author: "김수진",
      authorEmail: "sujin@example.com",
      body: "뉴스피크 개념이 소름 돋았어요. 언어를 제한하면 생각도 제한된다는 것.",
      createdAt: "2026-04-26T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-013-3",
      reviewId: "rev-013",
      author: "최민준",
      authorEmail: "minjun@example.com",
      body: "동물 농장도 함께 읽으면 오웰의 세계관이 더 명확해져요.",
      createdAt: "2026-04-26T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-013-4",
      reviewId: "rev-013",
      author: "윤태호",
      authorEmail: "taeho@example.com",
      body: "2+2=5를 강요하는 장면이 가장 충격적이었어요.",
      createdAt: "2026-04-27T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-013-5",
      reviewId: "rev-013",
      author: "오나연",
      authorEmail: "nayeon@example.com",
      body: "고전이 왜 고전인지 알게 되는 책이에요.",
      createdAt: "2026-04-27T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-013-6",
      reviewId: "rev-013",
      author: "강서연",
      authorEmail: "seoyeon@example.com",
      body: "결말이 이렇게 암울해도 되는 건지... 하지만 그래야 더 강렬한 것 같아요.",
      createdAt: "2026-04-27T14:00:00.000Z",
      deleted: false,
    },
  ],
  "rev-014": [
    {
      id: "cmt-014-1",
      reviewId: "rev-014",
      author: "박현우",
      authorEmail: "hyunwoo@example.com",
      body: "삶을 다시 시작할 수 있다면 어떤 선택을 했을까 오래 생각하게 됐어요.",
      createdAt: "2026-04-28T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-014-2",
      reviewId: "rev-014",
      author: "정다연",
      authorEmail: "dayeon@example.com",
      body: "우울과 후회를 다루는 방식이 매우 따뜻해요.",
      createdAt: "2026-04-28T11:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-014-3",
      reviewId: "rev-014",
      author: "서준혁",
      authorEmail: "junhyuk@example.com",
      body: "지금 이 순간이 최선의 삶이라는 메시지를 받은 것 같았어요.",
      createdAt: "2026-04-28T14:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-014-4",
      reviewId: "rev-014",
      author: "임소현",
      authorEmail: "sohyun@example.com",
      body: "주인공 노라가 매력적인데, 감정 변화가 굉장히 섬세하게 그려졌어요.",
      createdAt: "2026-04-29T09:00:00.000Z",
      deleted: false,
    },
    {
      id: "cmt-014-5",
      reviewId: "rev-014",
      author: "한재민",
      authorEmail: "jaemin@example.com",
      body: "영어 원서로도 읽어보고 싶어졌어요.",
      createdAt: "2026-04-29T11:00:00.000Z",
      deleted: false,
    },
  ],
};
